name: CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: basic
          MYSQL_ROOT_PASSWORD: root_password
          options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.1
      
      - name: Install dependencies
        run: npm i

      - name: Run migrations
        run: npm run migration:run

      - name: Unit Test
        run: npm run test

      - name: E2E Test
        run: npm run test:e2e